matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: node_js
      node_js: "12"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      yarn install:builders && yarn lint
    fi
  - "yarn install:builders && yarn build"
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      yarn install:builders && yarn test
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      yarn install:sample && yarn test:integration
    else
      yarn install:sample && test:integration:mac
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
